version: '3'

services:
  frontend:
    image: usatpath01/vulnerable-photo-app-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - api_gateway
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK5-SMRL
    networks:
      - frontend_network

  api_gateway:
    image: usatpath01/vulnerable-photo-app-api-gateway:latest
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - photo_service
      - notification_service
      - recommendation_service
      - analytics_service
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK5-SMRL
    networks:
      - frontend_network
      - backend_network
      
  user_service:
    image: usatpath01/vulnerable-photo-app-user-service:latest
    environment:
      - DB_HOST=user_db
      - DB_USER=root
      - DB_PASSWORD=insecure_password
      - DB_NAME=users
    depends_on:
      - user_db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK3
    networks:
      - backend_network

  photo_service:
    image: usatpath01/vulnerable-photo-app-photo-service:latest
    environment:
      - DB_HOST=photo_db
      - DB_USER=root
      - DB_PASSWORD=insecure_password
      - DB_NAME=photos
    volumes:
      - photo_uploads:/app/uploads
    networks:
      - backend_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK2
    depends_on:
      - photo_db

  notification_service:
    image: usatpath01/vulnerable-photo-app-notification-service:latest
    environment:
      - REDIS_URL=redis://notification_cache
    depends_on:
      - notification_cache
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK5-SMRL
    networks:
      - backend_network

  recommendation_service:
    image: usatpath01/vulnerable-photo-app-recommendation-service:latest
    environment:
      - DB_CONNECTION_STRING=mongodb://recommendation_db:27017/recommendations
    depends_on:
      - recommendation_db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK2
    networks:
      - backend_network

  analytics_service:
    image: usatpath01/vulnerable-photo-app-analytics-service:latest
    environment:
      - ELASTICSEARCH_URL=http://analytics_db:9200
    depends_on:
      - analytics_db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK5-SMRL
    networks:
      - backend_network

  user_db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=insecure_password
      - MYSQL_DATABASE=users
    volumes:
      - user_db_data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK3
    networks:
      - backend_network

  photo_db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=insecure_password
      - MYSQL_DATABASE=photos
    volumes:
      - photo_db_data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK2
    networks:
      - backend_network

  notification_cache:
    image: redis:6-alpine
    networks:
      - backend_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK5-SMRL

  recommendation_db:
    image: mongo:4.4
    networks:
      - backend_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK2

  analytics_db:
    image: elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    networks:
      - backend_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK5-SMRL
  
  profile-service:
    image: usatpath01/vulnerable-photo-app-profile-service:latest
    ports:
      - "3000:3000"
    networks:
      - backend_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == new-WK3

networks:
  frontend_network:
  backend_network:
  # app_network:
  #   driver: overlay

volumes:
  user_db_data:
  photo_db_data:
  photo_uploads: